# Pre-created secret for admin user credentials
# Apply this before deploying the ClickHouse chart with values-exsiting-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-admin-credentials
  namespace: test-01
type: Opaque
stringData:
  admin-password: "password"
---
# You can also create the secret using kubectl:
# kubectl create secret generic clickhouse-admin-credentials \
#   --from-literal=admin-password="super_secure_admin_password_123"
