operator:
  enabled: false

clickhouse:
  antiAffinity: true
  zones:
    - us-east-1a
    - us-east-1b
  nodeSelector:
    node.kubernetes.io/instance-type: "m6i.large"
  persistence:
    enabled: true
    size: 50Gi
    storageClass: gp3-encrypted
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "clickhouse"
      effect: "NoSchedule"

keeper:
  enabled: true
  replicaCount: 3
  zoneSpread: false
  localStorage:
    size: 5Gi
    storageClass: gp3-encrypted
  metricsPort: "7000"
  settings:
    prometheus/endpoint: /metrics
    prometheus/port: 7000
    prometheus/metrics: true
    prometheus/events: true
    prometheus/asynchronous_metrics: true
    prometheus/status_info: true
  podAnnotations:
    prometheus.io/port: "7000"
    prometheus.io/scrape: "true"
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "clickhouse"
      effect: "NoSchedule"
  resources:
    cpuRequestsMs: 1
    memoryRequestsMiB: 1Gi
    cpuLimitsMs: 2
    memoryLimitsMiB: 3Gi
