# -- Number of database replicas.
# For replication, `clickhouse-keeper.enabled` must be `true` to enable the built-in keeper
# or a hostname for keeper must be explicitly set under `keeper.host`
# The built-in keeper will automatically be enabled if replicaCount > 1 and a hostname is not provided
replicaCount: 1

clickhouse:
  defaultUser:
    user: "default"
    password: ""
    # -- Allow the default user to access ClickHouse from any IP.
    # If set, will override `hostIP` to always be `0.0.0.0/0`.
    allowExternalAccess: false
    # defaultUser.hostIP -- (string) Set a mask for IPs allowed for the default user.
    # Should not be set if allowExternalAccess is set.
    # @default -- 127.0.0.1/32
    hostIP: 

  # -- Keeper connection settings.
  keeper:
    # -- Specify a keeper host.
    # Should be left empty if `clickhouse-keeper.enabled` is `true`.
    # Will override the defaults set from `clickhouse-keeper.enabled`.
    host: ""
    # -- Override the default keeper port
    port: 2181



persistence:
  # -- enable storage
  enabled: true
  # -- volume size (per replica)
  size: 10Gi
  accessMode: ReadWriteOnce
  ## -- StorageClass for PV (e.g. gp2, standard, ...)
  storageClass: ""
  logs:
    # -- enable pvc for logs
    enabled: false
    # -- size for logs pvc
    size: 10Gi
    accessMode: ReadWriteOnce


# Specify which zones to run in.
# `replicaCount` will applied within each zone.
zones: []

image:
  repository: altinity/clickhouse-server
  pullPolicy: IfNotPresent
  # -- Override the image tag for a specific version
  tag: "23.8.8.21.altinitystable"

service:
  # e.g. `LoadBalancer`, `NodePort`
  type: ClusterIP

# By default pods will prefer to run on a node with no other CH instances
podDistribution:
  - type: ClickHouseAntiAffinity
    scope: ClickHouseInstallation

# @ignore
imagePullSecrets: []

# @ignore
nameOverride: ""

# @ignore
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

# @ignore
podSecurityContext: {}
  # runAsUser: 101
  # runAsGroup: 101

# @ignore
securityContext: {}

# @ignore
nodeSelector: {}

# @ignore
tolerations: []

# @ignore
affinity: {}

keeper:
  # -- Whether to enable Keeper.
  # Required for replicated tables.
  enabled: false
  # -- Number of keeper replicas.
  # Must be an odd number.
  # !! DO NOT CHANGE AFTER INITIAL DEPLOYMENT
  replicaCount: 3

operator:
  # -- Whether to enabled the Altinity Operator for ClickHouse.
  # Disable if you already have the Operator installed cluster-wide.
  enabled: true
