apiVersion: v2
name: clickhouse-eks
description: A Helm chart for ClickHouse running on AWS EKS across AZs using a nodeSelector to pin resources to run on specific VMs types
type: application
version: 0.1.1
appVersion: "1.16.0"

# dependencies:
#   - name: keeper-ss
#     version: ">=0.1.0"
#     repository: "https://altinity.github.io/kubernetes-blueprints-for-clickhouse/keeper-ss"