{{- $service_name := tpl (include "clickhouse.serviceTemplateName" . ) . -}}
---
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallationTemplate
metadata:
  name: {{ $service_name }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  templates:
    serviceTemplates:
      - name: "{{ $service_name }}"
        metadata:
          {{- with .Values.clickhouse.service.serviceAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "clickhouse.labels" . | nindent 12 }}
            {{- with .Values.clickhouse.service.serviceLabels }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
        spec:
          type: {{ .Values.clickhouse.service.type }}
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000
          selector:
            {{- include "clickhouse.selectorLabels" . | nindent 12 }}
{{- if .Values.clickhouse.lbService.enabled }}
---
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallationTemplate
metadata:
  name: "{{ $service_name }}-lb"
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  templates:
    serviceTemplates:
      - name: "{{ $service_name }}-lb"
        metadata:
          labels:
            {{- include "clickhouse.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
            {{- with .Values.clickhouse.lbService.serviceLabels }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- with .Values.clickhouse.lbService.serviceAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          type: "LoadBalancer"
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000
          selector:
            {{- include "clickhouse.selectorLabels" . | nindent 12 }}
{{- end }}
