{{- if or (not .Values.clickhouse.defaultUser.existingSecret) (not .Values.clickhouse.adminUser.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.credentialsName" . }}
type: Opaque
stringData:
  {{- if not .Values.clickhouse.defaultUser.existingSecret }}
  user: "default"
  password: "{{ .Values.clickhouse.defaultUser.password }}"
  {{- end }}
  {{- if not .Values.clickhouse.adminUser.existingSecret }}
  admin-user: "admin"
  admin-password: "{{ .Values.clickhouse.adminUser.password }}"
  {{- end }}
{{- end }}