{{- if not .Values.clickhouse.defaultUser.password_secret_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.credentialsName" . }}
type: Opaque
stringData:
  user: "default"
  password: "{{ .Values.clickhouse.defaultUser.password }}"
{{- end }}
