{{- if .Values.clickhouse.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouse.serviceAccountName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  {{- with .Values.clickhouse.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}