---
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallation
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  defaults:
    templates:
      serviceTemplate: {{ include "clickhouse.serviceTemplateName" . }}
      podTemplate: {{ include "clickhouse.podTemplateName" . }}
      {{- if .Values.persistence.enabled }}
      dataVolumeClaimTemplate: {{ include "clickhouse.volumeClaimTemplateName" . }}
      {{- end }}
  useTemplates:
    - name: {{ include "clickhouse.serviceTemplateName" . }}
    - name: {{ include "clickhouse.podTemplateName" . }}
    - name: {{ include "clickhouse.volumeClaimTemplateName" . }}

  configuration:
    users:
      {{ .Values.defaultUser.user }}/networks/ip: {{ include "clickhouse.defaultUser.ip" . | quote }}
      {{ .Values.defaultUser.user }}/access_management: 1
      {{ .Values.defaultUser.user }}/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-credentials
            key: password
    clusters:
      - name: {{ include "clickhouse.clustername" . }}
        layout:
          shardsCount: 1
          replicasCount: {{ .Values.replicaCount }}
    {{- if ".Values.clickhouse-keeper.enabled" }}
    zookeeper:
        nodes:
        - host: {{ include "clickhouse.keeper.host" . }}
          port: 2181
    {{- end }}
