---
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallation
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  defaults:
    templates:
      serviceTemplate: {{ include "clickhouse.serviceTemplateName" . }}
      podTemplate: {{ include "clickhouse.podTemplateName" . }}
      {{- if .Values.persistence.enabled }}
      volumeClaimTemplate: {{ include "clickhouse.volumeClaimTemplateName" . }}
      {{- end }}
    users:
      {{ .Values.clickhouse.defaultUser.user }}/networks/ip: {{ include "clickhouse.defaultUser.ip" . | quote }}
      {{ .Values.clickhouse.defaultUser.user }}/access_management: 1
      {{ .Values.clickhouse.defaultUser.user }}/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-credentials
            key: password
    clusters:
      - name: {{ include "clickhouse.fullname" . }}
        layout:
          shards:
            - replicas: {{ .Values.replicaCount }}
    {{- if ".Values.clickhouse-keeper.enabled" }}
    zookeeper:
        nodes:
        - host: "{{ include "clickhouse-keeper.fullname" . }}"
          port: 2181
    {{- end }}
