apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.credentialsName" . }}
type: Opaque
stringData:
  user: "{{ .Values.clickhouse.defaultUser.user }}"
  password: "{{ .Values.clickhouse.defaultUser.password }}"
