apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
type: Opaque
stringData:
  user: "{{ .Values.clickhouse.defaultUser.user }}"
  password: "{{ .Values.clickhouse.defaultUser.password }}"
